### ISSUE TITLE
demo工程报错

### ISSUE THREAD

**Issue by Tonsjkjkas** [chenxing640/CXNetwork-Moya#1]
从 github 下载的example工程，pod install 直接报错，麻烦看一下

**Comment by Tonsjkjkas** [comment]
![Uploading 1715146402650.jpg…]()

**Comment by Tonsjkjkas** [comment]
![1715146402650](https://github.com/chenxing640/CXNetwork-Moya/assets/143983937/eea4cb5d-af3b-4981-9f99-7d797f1012b6)

**Comment by itenfay** [comment]
你升级一下CocoaPods试一下
<img width="566" alt="2024-05-08_13_49_21" src="https://github.com/chenxing640/CXNetwork-Moya/assets/15623781/8e7d3220-52c7-48e8-bea4-2ae333cab1ce">

**Comment by itenfay** [comment]
你可以看下以下文章操作：
- [CocoaPods 报错 pod install JSON::ParserError](https://www.jianshu.com/p/fb0237cc8c29)
- [cocoapods报错JSON::ParserError](https://www.jianshu.com/p/b2442a616c62)
